# Uncomment the next line to define a global platform for your project
platform :osx, "10.9"

target 'AmicusDeliveryInterface' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AmicusDeliveryInterface
  pod "PubNub", "~> 4.1"

end
